import type { Metadata } from "next";
import "./globals.css";
import EditDrawer from "@/components/edit-drawer/edit-drawer";
import { Navbar } from "@/components/navbar/navbar";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: [
    {
      url: "/images/logo.svg",
      href: "/images/logo.svg",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body>
      <Navbar />
      <main>{children}</main>
      <EditDrawer />
    </body>
  </html>
  );
}
