import type { Metadata } from "next"
import "./globals.css"
import { Navbar } from "@/components/navbar/navbar"
import { Sidebar } from "@/components/sidebar/sidebar"
// eslint-disable-next-line import/order
import { ClerkProvider } from "@clerk/nextjs"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: [
    {
      url: "/images/logo.svg",
      href: "/images/logo.svg",
    },
  ],
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
      <body>
        <main className="flex size-full">
            <div className="size-full">{children}</div>
        </main>
      </body>
    </html>
    </ClerkProvider>
  )
}
