import type { Metadata } from "next"

export const metadata: Metadata = {
  title: "Bookmarks | Dashboard",
  description: "Generated by create next app",
  icons: [
    {
      url: "/images/logo.svg",
      href: "/images/logo.svg",
    },
  ],
}
export default function DashboardLayout({ children }: React.PropsWithChildren) {
  return (
    <div className="size-full flex">{children}</div>
  )
}
