import type { Metadata } from "next"
import { ServerForm } from "@/components/server-form/server-form"
import { Sidebar } from "@/components/sidebar/sidebar"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: [
    {
      url: "/images/logo.svg",
      href: "/images/logo.svg",
    },
  ],
}

export default function BookmarkLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className="flex w-full">
      <div className="border">
        <Sidebar />
      </div>
      <div className="container">
        <div className="z-10">
          {/* <ServerForm /> */}
        </div>
        <div>{children}</div>
      </div>
    </div>
  )
}
