import type { Metadata } from "next"

import { Navbar } from "./_components/navbar/navbar";
export const metadata: Metadata = {
  title: "Add a new bookmark",
  description: "Generated by create next app",
  icons: [
    {
      url: "/images/logo.svg",
      href: "/images/logo.svg",
    },
  ],
}
export default function DashBoardLayout({ children }: React.PropsWithChildren) {
  return (
    <div className="crap h-screen min-h-screen flex flex-col overflow-hidden">
      <Navbar />
      <div className="flex  flex-1 flex-row w-full bg-slate-500 overflow-y-hidden">
        {children}
      </div>
      <footer className="flex w-full h-auto bg-slate-600 text-sm text-white p-2">2024</footer>
    </div>
  )
}
