import type { Metadata } from "next"

import { Navbar } from "./_components/navbar/navbar";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: [
    {
      url: "/images/logo.svg",
      href: "/images/logo.svg",
    },
  ],
}
export default function DashBoardLayout({ children }: React.PropsWithChildren) {
  return (
    <div className="h-screen min-h-screen flex flex-col overflow-hidden">
      <Navbar />
      <div className="flex flex-row w-full border-2 border-black bg-slate-500 overflow-y-hidden">
        {children}
      </div>
      <footer className="w-full h-5 bg-slate-600">I am a footer</footer>
    </div>
  )
}
